/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layoutclass;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author iit
 */
public class FaceBookFrame extends javax.swing.JFrame {

    private static String FIXED_firstName;
    private static String FIXED_surName;
    private static String FIXED_mobile;
    private static String FIXED_password;
    private final Color INACTOVE_COLOR = Color.gray;
    private final Color ACTIVE_COLOR = Color.BLACK;
    
    private String firstName;
    private String surName;
    private String mobile;
    private String password;
    private String day;
    private String month;
    private String year;
    private String Gender;
    private String fileName = "input.txt";
    private String allInformation;

    /**
     * Creates new form FaceBookFrame
     */
    public FaceBookFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreateAccount = new javax.swing.JLabel();
        labelFree = new javax.swing.JLabel();
        textFieldFirstName = new javax.swing.JTextField();
        textFieldSurname = new javax.swing.JTextField();
        textFieldMobile = new javax.swing.JTextField();
        textFieldPassword = new javax.swing.JTextField();
        lblBirtday = new javax.swing.JLabel();
        jComboBoxDate = new javax.swing.JComboBox<>();
        jComboMonth = new javax.swing.JComboBox<>();
        jComboYear = new javax.swing.JComboBox<>();
        jCheckBoxFemale = new javax.swing.JCheckBox();
        jCheckBoxMale = new javax.swing.JCheckBox();
        jButtonCreateAccount = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCreateAccount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCreateAccount.setText("Create An Account");

        labelFree.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelFree.setText("It's Free and always will be");

        textFieldFirstName.setText("First Name");
        textFieldFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldFirstNameFocusLost(evt);
            }
        });
        textFieldFirstName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textFieldFirstNameMouseClicked(evt);
            }
        });

        textFieldSurname.setText("Surname");
        textFieldSurname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldSurnameFocusLost(evt);
            }
        });
        textFieldSurname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textFieldSurnameMouseClicked(evt);
            }
        });
        textFieldSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldSurnameActionPerformed(evt);
            }
        });

        textFieldMobile.setText("Mobile or Email");
        textFieldMobile.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldMobileFocusLost(evt);
            }
        });
        textFieldMobile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textFieldMobileMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textFieldMobileMouseExited(evt);
            }
        });

        textFieldPassword.setText("New Password");
        textFieldPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldPasswordFocusLost(evt);
            }
        });
        textFieldPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textFieldPasswordMouseClicked(evt);
            }
        });

        lblBirtday.setText("Birtday");

        jComboBoxDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCheckBoxFemale.setText("Female");
        jCheckBoxFemale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxFemaleMouseClicked(evt);
            }
        });

        jCheckBoxMale.setText("Male");
        jCheckBoxMale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxMaleMouseClicked(evt);
            }
        });

        jButtonCreateAccount.setText("Create An Account");
        jButtonCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateAccountActionPerformed(evt);
            }
        });

        jButton1.setText("Show Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFree)
                    .addComponent(lblCreateAccount))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblBirtday)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBoxFemale))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxMale)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jButtonCreateAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(textFieldMobile, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textFieldPassword, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelFree, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(textFieldMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBirtday, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxFemale)
                    .addComponent(jCheckBoxMale))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCreateAccount)
                    .addComponent(jButton1))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldSurnameActionPerformed

  
    
    private void jButtonCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateAccountActionPerformed
        // TODO add your handling code here:
       // System.out.println("layoutclass.FaceBookFrame.jButtonCreateAccountActionPerformed()");
        firstName = textFieldFirstName.getText();
        surName = textFieldSurname.getText();
        mobile = textFieldMobile.getText();
        password = textFieldPassword.getText();
        day = (String) jComboBoxDate.getSelectedItem();
        month = (String) jComboMonth.getSelectedItem();
        year = (String) jComboYear.getSelectedItem();
        boolean isSelected = false;
        
        if(jCheckBoxFemale.isSelected()){
            Gender = "Female";
                    
            isSelected = true;
        }
        if(jCheckBoxMale.isSelected()){
            Gender = "Male";
            isSelected = true;
        }

        if (firstName.equals(FIXED_firstName) || firstName.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter first name");
            return;
        }
        if (surName.equals(FIXED_surName) || surName.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter Surname");
            return;
        }
        if (mobile.equals(FIXED_mobile) || mobile.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter Mobile or email");
            return;
        }
        if (password.equals(FIXED_password) || password.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter  Password");
            return;
        }

        if (day.equals("Day")) {
            JOptionPane.showMessageDialog(this, "Day is not entered");
            return;
        }
        if (month.equals("Month")) {
            JOptionPane.showMessageDialog(this, "Month is not entered");
            return;
        }
        if (year.equals("Year")) {
            JOptionPane.showMessageDialog(this, "Year is not entered");
            return;
        }
        if(isSelected == false){
            JOptionPane.showMessageDialog(this, "Select Gender");
            return;
        }
        System.out.println("Account Created successfully");
        
//        System.out.println("First Name: " + firstName);
//        System.out.println("Surname " + surName);
//        System.out.println("Email or mobile " + mobile);
//        System.out.println("Password " + password);
        allInformation = firstName + ", " + surName + ", " + mobile + ", " + password +", " +
                day + "-" + month + "-" + year + ", "+ Gender;
       saveInformationTofile();
        setVisible(false);
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                Information info = new Information();
//                info.setLabelFirstName(firstName);
//                info.setLaberSurName(surName);
//                info.setLabelEmail(mobile);
//                info.setGender(Gender);
//                info.setBirtDate(day, month, year);
//                info.setVisible(true);
////                new Information().setVisible(true);
//            }
//        });
        
        //System.out.println("Gender " + Gender);

//            String textFieldMobile = textFieldMobile.getText();
//            String textFieldPassword = text
    }//GEN-LAST:event_jButtonCreateAccountActionPerformed

    void  saveInformationTofile(){
        try {
            FileWriter writer = new FileWriter(fileName, true);
            BufferedWriter bufferedWriter = new BufferedWriter(writer);
 
            bufferedWriter.write(allInformation);
            bufferedWriter.newLine();
//            bufferedWriter.write("Thank You Again!");
 
            bufferedWriter.close();
        } catch (IOException e) {
            e.printStackTrace();
        } 
    }
    
    void readInformation(){
        try {
            FileReader reader = new FileReader(fileName);
            BufferedReader bufferedReader = new BufferedReader(reader);
 
            String line;
            String info[];
            int counter = 1;
            List<PersonalInfo> informationList = new ArrayList<PersonalInfo>();
            PersonalInfo personalInfo;
            while ((line = bufferedReader.readLine()) != null) {
                info = line.split(",");
//                System.out.println("First Name: " + info[0]);
//                System.out.println("Sur Name: " + info[1]);
//                System.out.println("Email: " + info[2]);
//                System.out.println("Birt Date: " + info[4]);
//                System.out.println("Gender: "+ info[5]);
                personalInfo = new PersonalInfo();
                personalInfo.firstName = info[0];
                personalInfo.surName = info[1];
                personalInfo.emai = info[2];
                personalInfo.birtDate = info[4];
                personalInfo.gender = info[5];
                
                informationList.add(personalInfo);
              
            }
            
            int i;
            for(i = 0; i < informationList.size(); i++){
                System.out.println("First Name: " + informationList.get(i).firstName);
                System.out.println("Sur Name: " + informationList.get(i).surName);
                System.out.println("Email: " + informationList.get(i).emai);
                System.out.println("Birt Date: " + informationList.get(i).birtDate);
                System.out.println("Gender: "+ informationList.get(i).gender);
                System.out.println("");
                System.out.println("");
            }
            
               java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                PersonalInfoModel model = new PersonalInfoModel(informationList);
                InformationInTable table = new InformationInTable(model);
                table.setVisible(true);
//                new Information().setVisible(true);
            }
        });
            
            reader.close();
 
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private void textFieldFirstNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldFirstNameMouseClicked
        // TODO add your handling code here:
//        if(firstName != null || firstName.isEmpty()){
//        }
        if(textFieldFirstName.getText().endsWith(FIXED_firstName)){
            textFieldFirstName.setText("");
        }
    }//GEN-LAST:event_textFieldFirstNameMouseClicked

    private void textFieldSurnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldSurnameMouseClicked
        // TODO add your handling code here:
        
        if(Objects.equals(textFieldSurname.getText(), FIXED_surName)){
            textFieldSurname.setText("");
        }
    }//GEN-LAST:event_textFieldSurnameMouseClicked

    private void textFieldMobileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldMobileMouseClicked
        // TODO add your handling code here:
        textFieldMobile.setText("");
    }//GEN-LAST:event_textFieldMobileMouseClicked

    private void jCheckBoxFemaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxFemaleMouseClicked
        // TODO add your handling code here:
        jCheckBoxMale.setSelected(false);
    }//GEN-LAST:event_jCheckBoxFemaleMouseClicked

    private void jCheckBoxMaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxMaleMouseClicked
        // TODO add your handling code here:
        jCheckBoxFemale.setSelected(false);
    }//GEN-LAST:event_jCheckBoxMaleMouseClicked

    private void textFieldMobileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldMobileMouseExited
        // TODO add your handling code here:
//        if(textFieldFirstName.getText().equals("")){
//            textFieldFirstName.setText(FIXED_firstName);
//        }
    }//GEN-LAST:event_textFieldMobileMouseExited

    private void textFieldFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldFirstNameFocusLost
        // TODO add your handling code here:
        if(textFieldFirstName.getText().equals("")){
            textFieldFirstName.setText(FIXED_firstName);
        }
    }//GEN-LAST:event_textFieldFirstNameFocusLost

    private void textFieldSurnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldSurnameFocusLost
        // TODO add your handling code here:
        if(textFieldSurname.getText().equals("")){
            textFieldSurname.setText(FIXED_surName);
        }
    }//GEN-LAST:event_textFieldSurnameFocusLost

    private void textFieldMobileFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldMobileFocusLost
        // TODO add your handling code here:
        if(textFieldMobile.getText().equals("")){
            textFieldMobile.setText(FIXED_mobile);
        }
    }//GEN-LAST:event_textFieldMobileFocusLost

    private void textFieldPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldPasswordMouseClicked
        // TODO add your handling code here:
        textFieldPassword.setText("");
    }//GEN-LAST:event_textFieldPasswordMouseClicked

    private void textFieldPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldPasswordFocusLost
        // TODO add your handling code here:
        if(textFieldPassword.getText().equals("")){
            textFieldPassword.setText(FIXED_password);
        }
    }//GEN-LAST:event_textFieldPasswordFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        readInformation();
        
             
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public void setFirstNameTextFiels(){
        textFieldFirstName.setBackground(INACTOVE_COLOR);
    }
    public void getFixedText() {

        FIXED_firstName = textFieldFirstName.getText();
        FIXED_surName = textFieldSurname.getText();
        FIXED_mobile = textFieldMobile.getText();
        FIXED_password = textFieldPassword.getText();
        
        
    }

    public void initComboBox() {
        int i;
        jComboBoxDate.removeAllItems();
        jComboBoxDate.addItem("Day");
        for (i = 1; i < 32; i++) {

            jComboBoxDate.addItem(Integer.toString(i));
        }
        jComboMonth.removeAllItems();
        jComboMonth.addItem("Month");
        String monthArray[] = {"Jan", "Feb", "Mar", "April", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"};
        for (String s : monthArray) {
            jComboMonth.addItem(s);
        }
        jComboYear.removeAllItems();
        jComboYear.addItem("Year");
        for (i = 1900; i < 2017; i++) {
            jComboYear.addItem(Integer.toString(i));
        }
    }

    void launchSignUp(){
        getFixedText();
        initComboBox();
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FaceBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FaceBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FaceBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FaceBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                FaceBookFrame faceBookFrame = new FaceBookFrame();
//                faceBookFrame.getFixedText();
//                faceBookFrame.initComboBox();
//                faceBookFrame.setVisible(true);
//
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCreateAccount;
    private javax.swing.JCheckBox jCheckBoxFemale;
    private javax.swing.JCheckBox jCheckBoxMale;
    private javax.swing.JComboBox<String> jComboBoxDate;
    private javax.swing.JComboBox<String> jComboMonth;
    private javax.swing.JComboBox<String> jComboYear;
    private javax.swing.JLabel labelFree;
    private javax.swing.JLabel lblBirtday;
    private javax.swing.JLabel lblCreateAccount;
    private javax.swing.JTextField textFieldFirstName;
    private javax.swing.JTextField textFieldMobile;
    private javax.swing.JTextField textFieldPassword;
    private javax.swing.JTextField textFieldSurname;
    // End of variables declaration//GEN-END:variables
}
